name: Passing Values Between Jobs

on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest

    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}

    steps:
      - id: step1
        run: echo "name=test" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "name=test"  >> $GITHUB_OUTPUT

  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: |
          echo "Printing the values"
          echo output1: ${{needs.job_1.outputs.output1}}
          echo output2: ${{needs.job_1.outputs.output2}}
